name: On Website Deploy
"on":
  push:
    branches:
      - "main"
jobs:
  build_and_deploy_web:
    name: Build & Deploy Flutter to Web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 🌍 Enable Web
        run: flutter config --enable-web

      - name: 📦 Get packages
        run: flutter pub get

      - name: 🏭 Build Web Application
        run: flutter build web --release

      - name: 🖥 Deploying to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_FESTIVAL_TURKIYE }}"
          channelId: live
          projectId: flutter-festival-turkiye
